# Configuration for application
php:
  PSR-1:
    enabled: true
    see: 'http://www.php-fig.org/psr/psr-1/'

AllCops:
  # Exclude:
  #    - '**/'
  files/phpTags:
    enabled: true
    description: >
      PHP code MUST use the long <?php ?> tags or the short-echo <?= ?> tags; it
      MUST NOT use the other tag variations.
    see: 'http://www.php-fig.org/psr/psr-1/#2-1-php-tags'
  files/phpEncoding:
    enabled: true
    description: >
      PHP code MUST use only UTF-8 without BOM.
    see: 'http://www.php-fig.org/psr/psr-1/#2-2-character-encoding'
  ccpm/methods:
    enabled: true
    description: >
      Method names MUST be declared in camelCase().
    see: 'http://www.php-fig.org/psr/psr-1/#4-3-methods'
  ccpm/constants:
    enabled: true
    description: >
      Class constants MUST be declared in all upper case with underscore
      separators.
    see: 'http://www.php-fig.org/psr/psr-1/#4-1-constants'
