# Configuration for application
php:
  # Precise PHP version
  version: 7
  # Precise convention used
  rules:
    - PSR-2
  # Precise framework used
  framework: zf-2

AllCops:
  # Exclude:
  #    - '**/'
  phpTags:
    enabled: true
    description: 'PHP Tags'
    see: 'http://www.php-fig.org/psr/psr-1/#2-1-php-tags'
  files/phpEncoding:
    enabled: true
    description: 'PHP code MUST use only UTF-8 without BOM.'
    see: 'http://www.php-fig.org/psr/psr-1/#2-2-character-encoding'
